version: "3.8"
services:
  app:
    build:
      context: app
      target: dev
    command: ["npm", "start"]
    volumes:
      - ./app:/src
      - /src/node_modules
    environment:
      REACT_APP_HOST: "http://app-provider:8000"
    stdin_open: true  # не понял зачем это ...
    ports:
      - "3000:3000"
