version: "3.8"
services:
  app:
    build:
      context: app
    command: ["npm", "start"]
    volumes:
      - ./app:/src
      - /src/node_modules
    stdin_open: true  # не понял зачем это ...
    ports:
      - "3000:3000"
